### ISSUE TITLE
Python code unused, abzgupta.pythonanywhere.com called?

### ISSUE THREAD

**Issue by 77it** [abzgupta/doughflow.io#3]
Hi, I was trying to see how the python code works and I found no deployment instruction.

Instead, I found in the JavaScript code [src/App.js](https://github.com/abzgupta/doughflow.io/blob/96e8b76a0a8333d337b9a62e428be9e25933ab35/src/App.js#L173) this line, calling an external service to execute the Python code.

```
const response = await axios.post(
        "https://abzgupta.pythonanywhere.com/get_financial_table_summarized",
        {
          property_list: properties,
        },
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

```

This is the intended way you intended to release the code?

Anyway, thanks for your work.

Stefano

**Comment by abzgupta** [comment]
Hi Stefano! 

Thanks for reaching out!

 I'll be honest - this was my first time pushing a personal app to a hosted server. I do not know what the best practices are. I needed a place to host the flask app, so I used PythonAnywhere.  I just wanted to get http://doughflow.io off the ground ASAP. I would love to learn the correct way to do this. So please let me know how to proceed, as this is the first time I am open-sourcing(and deploying) code. 

Thanks, 
abz

**Comment by 77it** [comment]
Hi, I work in finance, I develop local applications mostly in C# and JavaScript (Deno and Node.js) and I'm no expert about cloud delpoyment, but reading the documentation is not clear that the Python part is not automatically configured following the installation instructions.

If I were you I would clarify that the python part have to be hosted somewhere and you used PythonAnywhere; you can share the instruction on how you deployed with that platform, to help newbie that are not used to use Python cloud hosting.
